spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: portfolio
    password: portfolio
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    com.yourcompany: DEBUG

management:
  endpoint:
    health:
      show-details: always
